<?php
$a["archiveorg"]="(?:https?://)?(?:www\.)?archive.org/details/([^?/]+)(?:[?].*)?$";
$a["ard"]='^(?:https?://)?(?:(?:www\.)?ardmediathek\.de|mediathek\.daserste\.de)/(?:.*/)([^/\?]+)(?:\?.*)?';
$a["arte"]='(?:http://)?videos.arte.tv/(fr|de)/.*-(.*?).html';
$a["auengine"]='(?:http://)?(?:www\.)?auengine\.com/embed.php\?.*?file=([^&]+).*?';
$a["bandcamp"]='http://.*?\.bandcamp\.com/track/(.*)';
$a["bliptv"]='^(?:https?://)?(?:\w+\.)?blip\.tv/((.+/)|(play/)|(api\.swf#))(.+)$';
$a["breakcom"]='(?:http://)?(?:www\.)?break\.com/video/([^/]+)';
$a["brightcove"]='https?://.*brightcove\.com/(services|viewer).*\?(.*)';
$a["c56"]='https?://((www|player)\.)?56\.com/(.+?/)?(v_|(play_album.+-))(.+?)\.(html|swf)';
$a["canalplus"]='https?://www\.canalplus\.fr/.*?\?vid=(\d+)';
$a["collegehumor"]='^(?:https?://)?(?:www\.)?collegehumor\.com/(video|embed|e)/([0-9]+)/?(.*)$';
$a["comedycentral"]="^(:(tds|thedailyshow|cr|colbert|colbertnation|colbertreport)|(https?://)?(www\.)?(thedailyshow|colbertnation)\.com/(full-episodes/(.*)|((the-colbert-report-(videos|collections)/([0-9]+)/[^/]*/(.*?))|(watch/([^/]*)/(.*)))|(extended-interviews/([0-9]+)/playlist_tds_extended_(.*?)/.*?)))$";
	$a["condenast"]='http://(video|www).(%s).com/(watch|series|video)/(.+)';
	$a["criterion"]='https?://www\.criterion\.com/films/(\d*)-.+';
	$a["cspan"]='http://www.c-spanvideo.org/program/(.*)';
	$a["dailymotion"]='(?:https?://)?(?:www\.)?dailymotion\.[a-z]{2,3}/video/([^/]+)';
	$a["depositfiles"]='(?:http://)?(?:\w+\.)?depositfiles\.com/(?:../(#locale))?files/(.+)';
	$a["dotsub"]='(?:http://)?(?:www\.)?dotsub\.com/view/([^/]+)';
	$a["dreisat"]='(?:http://)?(?:www\.)?3sat.de/mediathek/index.php\?(?:(?:mode|display)=[^&]+&)*obj=([0-9]+)$';
	$a["ehow"]='(?:https?://)?(?:www\.)?ehow\.com/[^/_?]*_([0-9]+)';
	$a["eighttracks"]='https?://8tracks.com/([^/]+)/([^/#]+)(?:#.*)?$';
	$a["escapist"]='^(https?://)?(www\.)?escapistmagazine\.com/videos/view/([^/]+)/([^/?]+)[/?]?.*$';
	$a["exfm"]='(?:http://)?(?:www\.)?ex\.fm/song/([^/]+)';
    $a["soundcloud"] = '(?:http://)?(?:www\.)?api\.soundcloud.com/tracks/([^/]+)/stream';
	$a["facebook"]='^(?:https?://)?(?:\w+\.)?facebook\.com/(?:video/video|photo)\.php\?(?:.*?)v=(\d+)(?:.*)';
	$a["flickr"]='(?:https?://)?(?:www\.)?flickr\.com/photos/([\w\-_@]+)/(\d+).*';
	$a["freesound"]='(?:https?://)?(?:www\.)?freesound\.org/people/([^/]+)/sounds/([^/]+)';
	$a["funnyordie"]='^(?:https?://)?(?:www\.)?funnyordie\.com/videos/([0-9a-f]+)/.*$';
	$a["gamespot"]='(?:http://)?(?:www\.)?gamespot\.com/.*-(\d+)/?';
	$a["gametrailers"]='http://www.gametrailers.com/(videos|reviews|full-episodes)/(.*?)/(.*)';
	$a["googleplus"]='(?:https://)?plus\.google\.com/(?:[^/]+/)*?posts/(\w+)';
	$a["hotnewhiphop"]='http://www\.hotnewhiphop.com/.*\.(.*)\.html';
	$a["howcast"]='(?:https?://)?(?:www\.)?howcast\.com/videos/(\d+)';
	$a["hypem"]='(?:http://)?(?:www\.)?hypem\.com/track/([^/]+)/([^/]+)';
	$a["ign"]='https?://.+?\.ign\.com/(?:videos|show_videos)(/.+)?/(.+)';
	$a["ina"]='(?:http://)?(?:www\.)?ina\.fr/video/(I?[A-F0-9]+)/.*';
	$a["infoq"]='^(?:https?://)?(?:www\.)?infoq\.com/[^/]+/[^/]+$';
	$a["instagram"]='(?:http://)?instagram.com/p/(.*?)/';
	$a["jukebox"]='^http://www\.jukebox?\..+?\/.+[,]([a-z0-9\-]+).html';
	$a["justintv"]='^(?:http://)?(?:www\.)?(?:twitch|justin)\.tv/(?:([^/]+)|(?:(?:[^/]+)/b/([^/]+))|(?:(?:[^/]+)/c/([^/]+)))/?(?:\#.*)?$';
	$a["kankan"]='https?://(?:.*?\.)?kankan\.com/.+?/(\d+)\.shtml';
	$a["keek"]='https?://(?:www\.)?keek\.com/(?:!|\w+/keeks/)(\w+)';
	$a["liveleak"]='^(?:http?://)?(?:\w+\.)?liveleak\.com/view\?(?:.*?)i=([\w_]+)(?:.*)';
	$a["livestream"]='http://new.livestream.com/.*?/(.*?)(/videos/(\d+))?/?$';
	$a["metacafe"]='(?:http://)?(?:www\.)?metacafe\.com/watch/([^/]+)/([^/]+)/.*';
	$a["mixcloud"]='^(?:https?://)?(?:www\.)?mixcloud\.com/([\w\d-]+)/([\w\d-]+)';
	$a["mtv"]='^https?://(?:www\.)?mtv\.com/videos/.+?/([0-9]+)/[^/]+$';
	$a["muzu"]='https?://www.muzu.tv/(.+?)/(.+?)/(\d+)';
	$a["mypass"]='http://www.myspass.de/.*';
	$a["myvideo"]='(?:http://)?(?:www\.)?myvideo\.de/(?:[^/]+/)?watch/([0-9]+)/([^?/]+).*';
	$a["nba"]='^(?:https?://)?(?:watch\.|www\.)?nba\.com/(?:nba/)?video(/[^?]*?)(?:/index\.html)?(?:\?.*)?$';
	$a["ooyala"]='https?://.+?\.ooyala\.com/.*?embedCode=(.+?)(&|$)';
	$a["photobucket"]='(?:http://)?(?:[a-z0-9]+\.)?photobucket\.com/.*(([\?\&]current=)|_)(.*)\.((flv)|(mp4))';
	$a["pornotube"]='^(?:https?://)?(?:\w+\.)?pornotube\.com(/c/([0-9]+))?(/m/([0-9]+))(/(.+))$';
	$a["rbmaradio"]='https?://(?:www\.)?rbmaradio\.com/shows/([^/]+)$';
	$a["redtube"]='(?:http://)?(?:www\.)?redtube\.com/([0-9]+)';
	$a["ringtv"]='(?:http://)?(?:www\.)?ringtv\.craveonline\.com/videos/video/([^/]+)';
	$a["roxwel"]='https?://www\.roxwel\.com/player/(.+?)(\.|\?|$)';
	$a["sina"]='https?://(.*?\.)?video\.sina\.com\.cn/((.+?/(((\d+).html)|(.*?(\#|(vid=))(\d+?)($|&))))|(api/sinawebApi/outplay.php/(.+?)\.swf))';
	$a["soundcloud"]='^(?:https?://)?(?:(?:(?:www\.)?soundcloud\.com/([\w\d-]+)/([\w\d-]+)/?(?:[?].*)?$)|(?:api\.soundcloud\.com/tracks/(\d+)))';
	$a["spiegel"]='https?://(?:www\.)?spiegel\.de/video/[^/]*-([0-9]+)(?:\.html)?(?:#.*)?$';
	$a["stanfordoc"]='^(?:https?://)?openclassroom.stanford.edu(/?|(/MainFolder/(?:HomePage|CoursePage|VideoPage)\.php([?]course=([^&]+)(&video=([^&]+))?(&.*)?)?))$';
	$a["statigram"]='(?:http://)?(?:www\.)?statigr\.am/p/([^/]+)';
	$a["stream"]='""http://store\.steampowered\.com/
                (agecheck/)?
                (video|app)/ 
                (\d+)/?
                (\d*)(\??)
                ""';
	$a["teamcoco"]='http://teamcoco\.com/video/(.*)';
	$a["ted"]='http://www\.ted\.com/
                   (
                        ((playlists)/(\d+))
                        |
                        ((talks)) 
                   )
                   (/lang/(.*?))? 
                   /(\w+)
                   ';
	$a["tf1"]='http://videos.tf1.fr/.*-(.*?).html';
	$a["thisav"]='https?://(?:www\.)?thisav\.com/video/([0-9]+)/.*';
	$a["traileraddict"]='(?:http://)?(?:www\.)?traileraddict\.com/(?:trailer|clip)/(.+?)/(.+)';
	$a["tudou"]='(?:http://)?(?:www\.)?tudou\.com/(?:listplay|programs)/(?:view|(.+?))/(?:([^/]+)|([^/]+))(?:\.html)?';
	$a["tumblr"]='http://(.*?)\.tumblr\.com/((post)|(video))/(\d*)/(.*?)';
	$a["tutv"]='https?://(?:www\.)?tu\.tv/videos/([^/?]+)';
	$a["ustream"]='https?://www\.ustream\.tv/recorded/(\d+)';
	$a["vbox7"]='(?:http://)?(?:www\.)?vbox7\.com/play:([^/]+)';
	$a["veoh"]='http://www\.veoh\.com/watch/v(\d*)';
	$a["vevo"]='((http://www.vevo.com/watch/.*?/.*?/)|(vevo:))(.*)$';
	$a["videofyme"]='https?://(www.videofy.me/.+?|p.videofy.me/v)/(\d+)(&|#|$)';
	$a["vimeo"]='(https?://)?(?:(?:www|player)\.)?vimeo(pro)?\.com/(?:(?:(?:groups|album)/[^/]+)|(?:.*?)/)?(play_redirect_hls\?clip_id=)?(?:videos?/)?([0-9]+)(?:[?].*)?$';
	$a["vine"]='(?:https?://)?(?:www\.)?vine\.co/v/(\w+)';
	$a["wat"]='http://www.wat.tv/.*-(.*?)_.*?.html';
	$a["weibo"]='https?://video\.weibo\.com/v/weishipin/t_(.+?)\.htm';
	$a["wimp"]='(?:http://)?(?:www\.)?wimp\.com/([^/]+)/';
	$a["worldstarhiphop"]='https?://(?:www|m)\.worldstar(?:candy|hiphop)\.com/videos/video\.php\?v=(.*)';
	$a["xhamster"]='(?:http://)?(?:www.)?xhamster\.com/movies/([0-9]+)/.*\.html';
	$a["xnxx"]='^(?:https?://)?video\.xnxx\.com/video([0-9]+)/(.*)';
	$a["xvideos"]='^(?:https?://)?(?:www\.)?xvideos\.com/video([0-9]+)(?:.*)';
	$a["yahoo"]='http://screen\.yahoo\.com/.*?-(\d*?)\.html';
	$a["youjizz"]='^(?:https?://)?(?:\w+\.)?youjizz\.com/videos/([^.]+).html$';
	$a["youku"]='(?:http://)?(v|player)\.youku\.com/(v_show/id_|player\.php/sid/)([A-Za-z0-9]+)(\.html|/v.swf)';
	$a["youporn"]='^(?:https?://)?(?:\w+\.)?youporn\.com/watch/([0-9]+)/([^/]+)';
	$a["youtube"]='^
                     (
                         (?:https?://)?
                         (?:youtu\.be/|(?:\w+\.)?youtube(?:-nocookie)?\.com/|
                            tube\.majestyc\.net/)
                         (?:.*?\#/)?
                         (?:
                             (?:(?:v|embed|e)/)
                             |(?:
                                 (?:watch|movie(?:_popup)?(?:\.php)?)?
                                 (?:\?|\#!?)
                                 (?:.*?&)?
                                 v=
                             )
                         )?
                     )?                         
                     ([0-9A-Za-z_-]+)           
                     ((1).+)?
                     $';
	$a["zdf"]='^http://www\.zdf\.de\/ZDFmediathek\/(.*beitrag\/video\/)([^/\?]+)(?:\?.*)?';
	//$a["generic"]='.*';
	echo(json_encode($a));
?>